= MongoDB Example

Example of running MongoDB locallly with Docker, for use as demo and exercises in the DM566 course at IMADA, SDU.

== Build and run

=== Mongo DB

Use the Docker-compose file to get Mongo DB up and running, including the interface where you can inspect it. Do this with this command:

 docker-compose up

You can add flag `-d` if you wish to run it as a deamon.

Stop and remove it using

 docker-compose kill

Mongo is now available on port 27017, and you can access the web GUI at http://localhost:8081/

=== Application

Run using

 ./gradlew run

Available commands are:

* *load* Loads the Pokemon dataset
* *scan* Lists the pokemon with their name and type (Type1)
* *id* Asks which id of pokemon you will see. #42 is _Golbat_


== Pokemon Example Data

The dataset is from here: https://www.kaggle.com/shoduro/pick-your-pokemon/data

== Exercises

The code is in Groovy, but you can program JAVA if you prefer this. Very few JAVA constructs are invalid Groovy (Up to JAVA 7).

You should find help in the documentation: http://mongodb.github.io/mongo-java-driver/3.6/

. Clone the repo, and try to run the code using `./gradlew run`
** Possible inputs are:
*** *load* Loads the Pokemon dataset
*** *scan* Lists the pokemon with their name and type (Type1)
*** *id* Asks which id of pokemon you will see. #42 is _Golbat_
.[X] Make the output format of the id task display prettier, and not just a printline of a map type.
.[X] Try to implement querying, so you can query by a type, and only gets pokemons of that type displayed.
. Add a seen column to the pokemon, and add a method where you can increment the number of times you have seen the different pokemons.
. Implement querying where you get listed all pokemons you have seen less times than/more times that a supplied number.
. Add a delete method where you can remove a pokemon from the dataset
. Add information on where you have seen a pokemon, so you can get a list of all the places you have seen it
** Make also an aggegate list, where you group by the location.
. Extend the location with a username, so you can use the database for many users
** And extract who have seen the pokemon how many times.

TIP: There should be plenty of exercises - this is by design, so you don't run out of ideas to implement in the tutorial session.


== Resources

* https://github.com/yeasy/docker-compose-files/blob/master/mongo_webui/docker-compose.yml
* https://devstacks.wordpress.com/2017/06/02/using-dockerised-mongodb-in-a-java-application/
* http://mongodb.github.io/mongo-java-driver/3.6/